version: "3.4"
services:
  frontend:
    image: chaitu1812/frontend-rhel9
    networks: &net ["expense"]
    depends_on: ["catalogue","user"]
    ports:
      - "80:80"

  load_schema:
    image: chaitu1812/load-schema-rhel9
    environment:
      CODE_URL: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      SCHEMA_FILE: "/app/db/master-data.js"
      MONGO_DB_ADDRESS: "mongodb"
    networks: *net
    depends_on:
      - 'mongodb'

  catalogue:
    image: chaitu1812/catalogue-rhel9
    networks: *net
    depends_on: ["mongodb"]
    environment:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb:27017/catalogue"

  mongodb:
    image: chaitu1812/mongo-rhel9
    networks: *net

  userd:
    image: chaitu1812/mongo-rhel9
    networks: *net
    depends_on: ["redis"]
    environment:
      - REDIS_URL="redis://redis:6379"
      - MONGO_URL="mongodb://mongod:27017/users"

  redis:
    image: chaitu1812/redis-rhel9
    networks: *net

networks:
  expense:
    external: true
