version: "3.4"
services:
  frontend:
    image: chaitu1812/frontend-rhel9
    networks: &net ["expense"]
    depends_on: ["catalogue","userd"]
    ports:
      - "80:80"

  load_schema:
    image: chaitu1812/load-schema-rhel9
    environment:
      component: "mongo"
      CODE_URL: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      SCHEMA_FILE: "/app/db/master-data.js"
      MONGO_DB_ADDRESS: "mongodb"
    networks: *net
    depends_on: ["mongodb"]

  catalogue:
    image: chaitu1812/catalogue-rhel9
    networks: *net
    depends_on: ["mongodb"]
    environment:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb:27017/catalogue"

  mongodb:
    image: chaitu1812/mongo-rhel9
    networks: *net

  userd:
    image: chaitu1812/user-rhel9
    networks: *net
    depends_on: ["redis"]
    environment:
       REDIS_URL: redis://redis:6379
       MONGO_URL: "mongodb://mongodb:27017/users"

  redis:
    image: chaitu1812/redis-rhel9
    networks: *net

  cart:
    image: chaitu1812/cart-rhel9
    networks: *net
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
      - redis
      - catalogue

  load_schema1:
    image: chaitu1812/load-schema-rhel9
    environment:
      component: "mysql"
      CODE_URL: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
      SCHEMA_FILE: "/app/db"
      MYSQL_ADDRESS: "mysql"
    networks: *net
    depends_on: [ "mongodb" ]

  shipping:
    image: chaitu1812/shipping-rhel9
    networks: *net


networks:
  expense:
    external: true
